import { Order } from "@/types";

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    customerName: "John Doe",
    email: "john@example.com",
    phone: "+39 02 1234567",
    address: "123 Gas St",
    city: "Milan",
    postalCode: "20121",
    country: "Italy",
    paymentMethod: "Credit Card",
    items: [{ productId: "p1", name: "Norval Series Regulator", price: 450, quantity: 2 }],
    subtotal: 900,
    shipping: 0,
    tax: 0,
    total: 900,
    status: "Delivered",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "ORD-002",
    customerName: "Sarah Smith",
    email: "sarah@gasworks.com",
    phone: "+49 30 9876543",
    address: "45 Pipeline Rd",
    city: "Berlin",
    postalCode: "10115",
    country: "Germany",
    paymentMethod: "Credit Card",
    items: [{ productId: "p2", name: "Dival 600", price: 320, quantity: 1 }],
    subtotal: 320,
    shipping: 0,
    tax: 0,
    total: 320,
    status: "Processing",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "ORD-003",
    customerName: "Mario Rossi",
    email: "technical@energycorp.it",
    phone: "+39 06 5550123",
    address: "Area Industriale",
    city: "Rome",
    postalCode: "00118",
    country: "Italy",
    paymentMethod: "Credit Card",
    items: [{ productId: "p3", name: "RS/2.4 Filter", price: 150, quantity: 5 }],
    subtotal: 750,
    shipping: 0,
    tax: 0,
    total: 750,
    status: "Shipped",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  }
];
