import { Product } from "@/types";

const images = [
  "https://fiorentinidb.com/wp-content/uploads/2021/03/00_product_main-2.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2024/01/PFDB-Meter.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2023/10/PF_metering.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2024/02/flowatch-3i.png",
  "https://fiorentinidb.com/wp-content/uploads/2023/10/systems.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2024/01/RENEWABLES_biogas.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2023/10/Gas-dehydration-liquid-technology-TEG-DEG-MEG_PietroFiorentini.png",
  "https://fiorentinidb.com/wp-content/uploads/2023/10/services.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2024/02/PietroFiorentiniASRetigas_BiremiFinaleEmilia_W.png",
  "https://fiorentinidb.com/wp-content/uploads/2024/01/Slide-2-mappa-mondo-Fiorentini-DB_1536x.803.png",
  "https://fiorentinidb.com/wp-content/uploads/2023/11/FAST_2023.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2024/07/BdS2023_Cover.png",
  "https://fiorentinidb.com/wp-content/uploads/2024/01/PFDB-Italy-Group-Photo.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2021/04/bg-company-2.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2020/11/bg-company.jpg"
];

const defaultGallery = [
  "https://fiorentinidb.com/wp-content/uploads/2024/01/Slide-3.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2021/04/bg-company-2.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2020/11/bg-company.jpg",
  "https://fiorentinidb.com/wp-content/uploads/2024/01/PFDB-Italy-Group-Photo.jpg"
];

export const products: Product[] = [
  {
    id: "prod-1",
    slug: "aperflux-251-ps",
    name: "Aperflux 251 PS",
    model: "APX-251-PS",
    price: 2500,
    category: "Pressure Regulators",
    stockStatus: "In Stock",
    stockQuantity: 45,
    rating: 4.8,
    reviewCount: 124,
    shortDescription: "High-pressure gas regulator for industrial networks",
    longDescription: "The Aperflux 251 PS is a high-performance gas pressure regulator designed for transmission pipelines up to 100 bar. Features balanced valve design for stable outlet pressure despite inlet variations.",
    specifications: {
      "Inlet Pressure": "10-100 bar",
      "Outlet Pressure": "0.5-50 bar",
      "Flow Capacity": "2500 Nm³/h",
      "Accuracy": "±1%",
      "Temperature Range": "-20°C to +60°C",
      "Material": "Cast iron + SS",
      "Connection": "DN50-DN150",
      "Certification": "ATEX, IECEx, PED",
    },
    features: [
      "Balanced valve design",
      "Integrated slam-shut option",
      "Low noise <65dB",
      "Maintenance-friendly",
      "H2 blend ready",
      "High accuracy class"
    ],
    applications: ["City gate stations", "Industrial plants", "Power generation"],
    imageId: images[0],
    galleryImages: [images[0], ...defaultGallery.slice(1)],
    downloads: [
      { name: "Technical Brochure", size: "2.4 MB", url: "#" },
      { name: "Installation Manual", size: "4.1 MB", url: "#" },
    ],
  },
  {
    id: "prod-2",
    slug: "minireg-m3",
    name: "Minireg M3",
    model: "MNR-M3",
    price: 890,
    category: "Pressure Regulators",
    stockStatus: "In Stock",
    stockQuantity: 120,
    rating: 4.6,
    reviewCount: 89,
    shortDescription: "Compact low-pressure regulator for residential use",
    longDescription: "Highly reliable low-pressure regulator tailored for residential applications, providing precise control and a compact footprint.",
    specifications: {
      "Inlet Pressure": "0.5-5 bar",
      "Outlet Pressure": "20-50 mbar",
      "Flow Capacity": "150 Nm³/h",
      "Accuracy": "±2%",
      "Temperature Range": "-20°C to +60°C",
      "Material": "Aluminum die-cast",
      "Connection": "DN25",
      "Certification": "PED",
    },
    features: [
      "Compact design",
      "Internal relief valve",
      "Easy installation",
      "Corrosion-resistant",
      "Direct acting",
      "Low maintenance"
    ],
    applications: ["Residential networks", "Small commercial", "Sub-metering"],
    imageId: images[1],
    galleryImages: [images[1], ...defaultGallery.slice(1)],
    downloads: [{ name: "Product Data Sheet", size: "1.2 MB", url: "#" }],
  },
  {
    id: "prod-3",
    slug: "fluxmaster-hp",
    name: "FluxMaster HP",
    model: "FLX-HP",
    price: 4300,
    category: "Pressure Regulators",
    stockStatus: "In Stock",
    stockQuantity: 18,
    rating: 4.9,
    reviewCount: 56,
    shortDescription: "High flow capacity for transmission lines",
    longDescription: "Top-tier high flow regulator for major transmission lines and regional distribution. Guarantees exceptional performance under varying load conditions.",
    specifications: {
      "Inlet Pressure": "20-150 bar",
      "Outlet Pressure": "5-80 bar",
      "Flow Capacity": "8000 Nm³/h",
      "Accuracy": "±0.5%",
      "Temperature Range": "-20°C to +60°C",
      "Material": "Carbon Steel",
      "Connection": "DN100-DN250",
      "Certification": "ATEX, PED",
    },
    features: [
      "Ultra-high capacity",
      "Fail-to-close design",
      "Whisper-quiet trim",
      "Pilot operated",
      "Heavy duty build",
      "Remote monitoring ready"
    ],
    applications: ["Transmission lines", "Border stations", "Heavy industry"],
    imageId: images[2],
    galleryImages: [images[2], ...defaultGallery.slice(1)],
    downloads: [{ name: "Spec Sheet", size: "3.5 MB", url: "#" }],
  },
  {
    id: "prod-4",
    slug: "regolux-pro",
    name: "Regolux Pro",
    model: "RGL-PRO",
    price: 3200,
    category: "Pressure Regulators",
    stockStatus: "In Stock",
    stockQuantity: 32,
    rating: 4.7,
    reviewCount: 45,
    shortDescription: "Advanced distribution pressure regulator",
    longDescription: "Versatile medium pressure regulator for district heating and local distribution networks. Fully modular design.",
    specifications: {
      "Inlet Pressure": "5-50 bar",
      "Outlet Pressure": "1-10 bar",
      "Flow Capacity": "4000 Nm³/h",
      "Accuracy": "±1%",
      "Temperature Range": "-20°C to +60°C",
      "Material": "Steel/Aluminum",
      "Connection": "DN80",
      "Certification": "PED",
    },
    features: ["Modular", "Quick trim replacement", "Built-in silencer", "Low hysteresis", "Robust design", "Spring loaded"],
    applications: ["District stations", "Commercial hubs", "Light industry"],
    imageId: images[3],
    galleryImages: [images[3], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-5",
    slug: "microgas-pr-50",
    name: "MicroGas PR-50",
    model: "MG-PR50",
    price: 1250,
    category: "Pressure Regulators",
    stockStatus: "In Stock",
    stockQuantity: 67,
    rating: 4.5,
    reviewCount: 112,
    shortDescription: "Precision lab-grade gas regulator",
    longDescription: "High precision regulator designed for clean environments and laboratory testing setups requiring extreme stability.",
    specifications: {
      "Inlet Pressure": "1-20 bar",
      "Outlet Pressure": "0.1-2 bar",
      "Flow Capacity": "500 Nm³/h",
      "Accuracy": "±0.2%",
      "Temperature Range": "-10°C to +50°C",
      "Material": "Stainless Steel 316L",
      "Connection": "DN15-DN25",
      "Certification": "ISO 9001",
    },
    features: ["Ultra precision", "Clean room ready", "Diaphragm type", "Teflon seals", "Micro-adjust dial", "No outgassing"],
    applications: ["Laboratories", "Medical gas", "High-tech manufacturing"],
    imageId: images[4],
    galleryImages: [images[4], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-6",
    slug: "ultraflow-xd",
    name: "UltraFlow XD",
    model: "UF-XD",
    price: 5800,
    category: "Pressure Regulators",
    stockStatus: "Low Stock",
    stockQuantity: 9,
    rating: 4.9,
    reviewCount: 31,
    shortDescription: "Extreme duty gas regulator",
    longDescription: "Built for the harshest environments. The UltraFlow XD handles extreme pressures and temperatures with ease.",
    specifications: {
      "Inlet Pressure": "50-250 bar",
      "Outlet Pressure": "10-100 bar",
      "Flow Capacity": "12000 Nm³/h",
      "Accuracy": "±1%",
      "Temperature Range": "-40°C to +80°C",
      "Material": "Forged Steel",
      "Connection": "DN150",
      "Certification": "API 6D",
    },
    features: ["Extreme durability", "Anti-freeze design", "Dual pilot", "Massive flow", "Shock resistant", "Telemetry compatible"],
    applications: ["Offshore rigs", "Desert pipelines", "Cryogenic backup"],
    imageId: images[5],
    galleryImages: [images[5], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-7",
    slug: "quantumflow-g6",
    name: "QuantumFlow G6",
    model: "QTF-G6",
    price: 550,
    category: "Gas Meters",
    stockStatus: "In Stock",
    stockQuantity: 200,
    rating: 4.7,
    reviewCount: 234,
    shortDescription: "Diaphragm gas meter for domestic applications",
    longDescription: "Precision-engineered diaphragm gas meter with high accuracy across wide flow range. Highly resistant to contamination.",
    specifications: {
      "Flow Capacity": "0.04-10 Nm³/h",
      "Accuracy": "±1.5%",
      "Pressure": "0.5 bar max",
      "Temperature Range": "-10°C to +50°C",
      "Material": "Steel casing",
      "Connection": "G 1 1/4",
      "Readout": "Mechanical index",
      "Certification": "MID",
    },
    features: ["Synthetic diaphragm", "Low pressure drop", "Magnetic coupling", "Anti-tamper", "Pulse output ready", "Long life span"],
    applications: ["Residential metering", "Small business", "Apartment complexes"],
    imageId: images[6],
    galleryImages: [images[6], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-8",
    slug: "smartgas-g16",
    name: "SmartGas G16",
    model: "SMG-G16",
    price: 980,
    category: "Gas Meters",
    stockStatus: "In Stock",
    stockQuantity: 89,
    rating: 4.8,
    reviewCount: 167,
    shortDescription: "IoT-enabled smart meter with remote reading",
    longDescription: "Next generation smart meter featuring integrated NB-IoT/LoRaWAN for real-time consumption data and remote diagnostics.",
    specifications: {
      "Flow Capacity": "0.1-25 Nm³/h",
      "Accuracy": "±1%",
      "Pressure": "0.5 bar max",
      "Temperature Range": "-25°C to +55°C",
      "Connectivity": "LoRaWAN / NB-IoT",
      "Battery Life": "10 years",
      "Data Rate": "Daily/Hourly",
      "Certification": "MID, ATEX",
    },
    features: ["Remote reading", "Valve control built-in", "Tamper alerts", "Encrypted data", "Firmware OTA", "LCD display"],
    applications: ["Smart cities", "Commercial buildings", "Utility modernization"],
    imageId: images[7],
    galleryImages: [images[7], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-9",
    slug: "industrial-rotary-g40",
    name: "Industrial Rotary G40",
    model: "IRM-G40",
    price: 2100,
    category: "Gas Meters",
    stockStatus: "In Stock",
    stockQuantity: 34,
    rating: 4.8,
    reviewCount: 78,
    shortDescription: "Rotary meter for commercial/industrial applications",
    longDescription: "Heavy-duty rotary positive displacement meter for precise measurement of industrial loads where rangeability is critical.",
    specifications: {
      "Flow Capacity": "0.6-65 Nm³/h",
      "Accuracy": "±1%",
      "Pressure": "16 bar max",
      "Temperature Range": "-25°C to +55°C",
      "Material": "Aluminum",
      "Connection": "DN50",
      "Rangeability": "1:100",
      "Certification": "MID, PED",
    },
    features: ["High rangeability", "Compact footprint", "Low frequency pulse", "Robust impellers", "Oil lubricated", "Vibration resistant"],
    applications: ["Industrial heating", "Process gas", "Skid units"],
    imageId: images[8],
    galleryImages: [images[8], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-10",
    slug: "ultrasync-g65",
    name: "UltraSync G65",
    model: "US-G65",
    price: 3400,
    category: "Gas Meters",
    stockStatus: "In Stock",
    stockQuantity: 12,
    rating: 4.9,
    reviewCount: 42,
    shortDescription: "Ultrasonic gas meter for high-precision custody transfer",
    longDescription: "Advanced ultrasonic metering technology offering no moving parts, zero pressure drop, and custody transfer accuracy.",
    specifications: {
      "Flow Capacity": "1-100 Nm³/h",
      "Accuracy": "±0.5%",
      "Pressure": "20 bar max",
      "Temperature Range": "-25°C to +60°C",
      "Technology": "Transit-time ultrasonic",
      "Power": "Solar/Battery combo",
      "Output": "Modbus RS485",
      "Certification": "MID, OIML",
    },
    features: ["No moving parts", "Self-diagnostics", "Bi-directional flow", "Wide dynamic range", "Maintenance free", "Digital twin ready"],
    applications: ["Custody transfer", "Pipeline monitoring", "Bio-gas measurement"],
    imageId: images[9],
    galleryImages: [images[9], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-11",
    slug: "thermal-mass-tm-200",
    name: "Thermal Mass TM-200",
    model: "TM-200",
    price: 4200,
    category: "Gas Meters",
    stockStatus: "Pre-order",
    stockQuantity: 0,
    rating: 4.6,
    reviewCount: 19,
    shortDescription: "Direct mass flow measurement meter",
    longDescription: "Thermal mass flow meter offering direct mass flow measurement independent of pressure and temperature variations.",
    specifications: {
      "Flow Capacity": "Up to 5000 kg/h",
      "Accuracy": "±1% of reading",
      "Pressure": "40 bar max",
      "Temperature Range": "-40°C to +150°C",
      "Sensor": "Platinum RTD",
      "Display": "OLED graphic",
      "Output": "4-20mA, HART",
      "Certification": "ATEX Zone 1",
    },
    features: ["Direct mass flow", "Wide turndown ratio", "Negligible pressure drop", "Insertion type", "Gas composition comp", "Hot tap ready"],
    applications: ["Flare gas", "Compressor efficiency", "Aeration basins"],
    imageId: images[10],
    galleryImages: [images[10], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-12",
    slug: "slamshut-ssv-a",
    name: "SlamShut SSV-A",
    model: "SSV-A72",
    price: 720,
    category: "Safety Valves",
    stockStatus: "In Stock",
    stockQuantity: 56,
    rating: 4.9,
    reviewCount: 92,
    shortDescription: "Safety shut-off valve with overpressure protection",
    longDescription: "Rapid response safety shut-off valve designed to completely stop gas flow in the event of over-pressure or under-pressure.",
    specifications: {
      "Response Time": "<1s",
      "Pressure Range": "0.1-100 bar",
      "Trip Accuracy": "±5%",
      "Temperature Range": "-20°C to +60°C",
      "Reset": "Manual only",
      "Material": "Carbon Steel",
      "Connection": "Flanged DN50",
      "Certification": "PED, SIL2",
    },
    features: ["Over/Under pressure", "Rapid closure", "Visual indicator", "Fail-safe", "Bypass for reset", "Compact design"],
    applications: ["Regulating stations", "Industrial burners", "Distribution networks"],
    imageId: images[11],
    galleryImages: [images[11], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-13",
    slug: "relief-valve-prx-25",
    name: "Relief Valve PRX 25",
    model: "PRX-25",
    price: 450,
    category: "Safety Valves",
    stockStatus: "Low Stock",
    stockQuantity: 5,
    rating: 4.7,
    reviewCount: 41,
    shortDescription: "Spring-loaded pressure relief valve",
    longDescription: "Direct acting relief valve to vent small volumes of gas to atmosphere, protecting downstream equipment from thermal expansion.",
    specifications: {
      "Set Pressure": "1-50 bar",
      "Relief Capacity": "150 Nm³/h",
      "Temperature Range": "-20°C to +80°C",
      "Material": "Stainless Steel",
      "Connection": "1\" NPT",
      "Seat": "Soft seat (Buna-N)",
      "Adjustment": "External screw",
      "Certification": "PED",
    },
    features: ["Bubble tight shutoff", "Field adjustable", "Tamper-proof cap", "Weatherproof", "High flow capacity", "Low blowdown"],
    applications: ["Skid protection", "Thermal relief", "Downstream safety"],
    imageId: images[12],
    galleryImages: [images[12], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-14",
    slug: "excess-flow-ef-50",
    name: "Excess Flow EF-50",
    model: "EF-50",
    price: 380,
    category: "Safety Valves",
    stockStatus: "In Stock",
    stockQuantity: 78,
    rating: 4.6,
    reviewCount: 33,
    shortDescription: "Automatic excess flow shut-off",
    longDescription: "Automatically closes when flow exceeds a predetermined limit, preventing catastrophic gas leaks in case of pipe rupture.",
    specifications: {
      "Trip Flow": "Configurable (10-500 Nm³/h)",
      "Max Pressure": "16 bar",
      "Temperature Range": "-20°C to +60°C",
      "Material": "Brass/Steel",
      "Connection": "DN50",
      "Reset": "Automatic bleed",
      "Pressure Drop": "Low",
      "Certification": "CE",
    },
    features: ["Pipe rupture protection", "Auto-reset capability", "In-line installation", "No external power", "Reliable mechanics", "Compact"],
    applications: ["Service lines", "Earthquake zones", "Industrial tapping"],
    imageId: images[13],
    galleryImages: [images[13], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-15",
    slug: "pilot-operated-psv-200",
    name: "Pilot Operated PSV-200",
    model: "PSV-200",
    price: 1900,
    category: "Safety Valves",
    stockStatus: "In Stock",
    stockQuantity: 23,
    rating: 4.8,
    reviewCount: 67,
    shortDescription: "High-capacity pilot operated safety valve",
    longDescription: "Provides highly accurate relief for transmission lines. Pilot operation ensures tight shut-off near the set pressure.",
    specifications: {
      "Set Pressure": "10-100 bar",
      "Relief Capacity": "8000 Nm³/h",
      "Temperature Range": "-20°C to +60°C",
      "Material": "Carbon Steel",
      "Connection": "DN100 Flange",
      "Action": "Pop or Modulating",
      "Sensing": "Remote sensing option",
      "Certification": "ASME Sec VIII",
    },
    features: ["Chatter-free", "High accuracy", "In-service testing", "Soft seated", "High capacity", "Field serviceable"],
    applications: ["Transmission lines", "Compressor stations", "Storage facilities"],
    imageId: images[14],
    galleryImages: [images[14], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-16",
    slug: "high-pressure-ssv-hp",
    name: "High-Pressure SSV-HP",
    model: "SSV-HP",
    price: 2300,
    category: "Safety Valves",
    stockStatus: "In Stock",
    stockQuantity: 11,
    rating: 4.9,
    reviewCount: 28,
    shortDescription: "Extreme pressure slam-shut valve",
    longDescription: "Robust slam-shut valve designed for extreme pressure applications up to 250 bar. Guarantees absolute safety.",
    specifications: {
      "Response Time": "<0.5s",
      "Pressure Range": "50-250 bar",
      "Trip Accuracy": "±2%",
      "Temperature Range": "-40°C to +80°C",
      "Reset": "Geared manual",
      "Material": "Forged Steel",
      "Connection": "RTJ Flanges",
      "Certification": "API 6D, SIL3",
    },
    features: ["Extreme pressure rated", "SIL3 certified", "Geared reset", "Corrosion resistant", "Dual sensing lines", "Fire safe design"],
    applications: ["Wellheads", "High pressure injection", "Gas processing"],
    imageId: images[15],
    galleryImages: [images[15], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-17",
    slug: "mgs-compact-4-0",
    name: "MGS Compact 4.0",
    model: "MGS-C40",
    price: 6800,
    category: "Hydrogen Systems",
    stockStatus: "In Stock",
    stockQuantity: 15,
    rating: 4.9,
    reviewCount: 34,
    shortDescription: "Modular multi-gas skid for hydrogen blending",
    longDescription: "Advanced skid unit designed for precise blending of Hydrogen into existing natural gas networks up to 30%.",
    specifications: {
      "H2 Compatibility": "Up to 100%",
      "Blending Ratio": "0-30%",
      "Flow Capacity": "5000 Nm³/h",
      "Pressure Max": "75 bar",
      "Control": "PLC based",
      "Material": "H2 specific steel",
      "Telemetry": "4G/5G/Ethernet",
      "Certification": "ATEX, H2 Ready",
    },
    features: ["Dynamic blending", "Real-time analysis", "Modular design", "Fail-safe shutdown", "Odorization integrated", "Remote control"],
    applications: ["Grid decarbonization", "Industrial H2 feed", "Power to Gas"],
    imageId: images[16],
    galleryImages: [images[16], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-18",
    slug: "dual-fuel-skid",
    name: "Dual Fuel Skid",
    model: "DFS-100",
    price: 12500,
    category: "Hydrogen Systems",
    stockStatus: "In Stock",
    stockQuantity: 6,
    rating: 4.8,
    reviewCount: 15,
    shortDescription: "Seamless switching between NG and H2",
    longDescription: "Industrial skid allowing seamless transition and mixing between natural gas and pure hydrogen for large scale burners.",
    specifications: {
      "H2 Compatibility": "100%",
      "Switching Time": "<5 seconds",
      "Flow Capacity": "10000 Nm³/h",
      "Pressure Max": "50 bar",
      "Control": "Redundant PLC",
      "Material": "SS 316L",
      "Sensors": "Fast response mass",
      "Certification": "SIL3",
    },
    features: ["Bumpless transfer", "Ratio control", "High safety integrity", "Integrated heating", "Customizable footprint", "Data logging"],
    applications: ["Steel mills", "Glass manufacturing", "Gas turbines"],
    imageId: images[17],
    galleryImages: [images[17], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-19",
    slug: "h2-ready-station",
    name: "H2 Ready Station",
    model: "H2-RS",
    price: 18900,
    category: "Hydrogen Systems",
    stockStatus: "Pre-order",
    stockQuantity: 0,
    rating: 5.0,
    reviewCount: 8,
    shortDescription: "Complete city gate station H2 ready",
    longDescription: "A fully integrated, turnkey pressure reduction and metering station certified for 100% Hydrogen operations.",
    specifications: {
      "H2 Compatibility": "100%",
      "Lines": "Active + Monitor + Bypass",
      "Flow Capacity": "20000 Nm³/h",
      "Pressure Drop": "100 bar to 5 bar",
      "Filtration": "Sub-micron H2 specific",
      "Heating": "Catalytic",
      "Enclosure": "Vented, ATEX",
      "Certification": "CE, H2 Ready full",
    },
    features: ["Turnkey solution", "Zero emission valves", "H2 embrittlement proof", "Smart metering", "Odorization", "Acoustic insulation"],
    applications: ["City gates", "Transmission nodes", "Green H2 valleys"],
    imageId: images[18],
    galleryImages: [images[18], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-20",
    slug: "hydrogen-refueling-microstation",
    name: "Hydrogen Refueling MicroStation",
    model: "HRS-M",
    price: 45000,
    category: "Hydrogen Systems",
    stockStatus: "Pre-order",
    stockQuantity: 0,
    rating: 4.7,
    reviewCount: 12,
    shortDescription: "Compact 350/700 bar H2 dispenser",
    longDescription: "Compact refueling solution for fleet depots. Dispenses hydrogen at 350 or 700 bar with integrated cooling.",
    specifications: {
      "Dispensing Pressure": "350/700 bar",
      "Capacity": "50 kg/day",
      "Cooling": "Integrated chiller (-40°C)",
      "Nozzle": "SAE J2600 compliant",
      "Metering": "Coriolis mass meter",
      "Payment": "RFID / Credit Card",
      "Footprint": "2m x 2m",
      "Certification": "OIML R 139",
    },
    features: ["Plug & Play", "Fast fill protocol", "Ultra-safe", "Cloud connected", "Low maintenance", "Touch screen interface"],
    applications: ["Forklift fleets", "Bus depots", "Private R&D"],
    imageId: images[19],
    galleryImages: [images[19], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-21",
    slug: "electrolyzer-interface-unit",
    name: "Electrolyzer Interface Unit",
    model: "EIU-500",
    price: 8900,
    category: "Hydrogen Systems",
    stockStatus: "In Stock",
    stockQuantity: 4,
    rating: 4.8,
    reviewCount: 22,
    shortDescription: "Grid integration for green hydrogen",
    longDescription: "Conditions hydrogen produced from electrolyzers (filtering, drying, metering) before injection into the gas grid.",
    specifications: {
      "Input Pressure": "10-30 bar",
      "Output Pressure": "Up to 80 bar (w/ compressor)",
      "Drying": "Twin tower desiccant",
      "Purity Monitor": "O2/H2O trace sensing",
      "Flow Capacity": "500 Nm³/h",
      "Material": "SS 316L",
      "Control": "Automated sequencing",
      "Certification": "ATEX Zone 2",
    },
    features: ["Moisture removal", "Trace gas analysis", "Buffer tank management", "Grid compliant output", "Skid mounted", "Scalable"],
    applications: ["Electrolyzer plants", "Wind/Solar to gas", "Biogas upgrades"],
    imageId: images[20],
    galleryImages: [images[20], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-22",
    slug: "gas-filter-gf-100",
    name: "Gas Filter GF-100",
    model: "GF-100",
    price: 290,
    category: "Filters & Strainers",
    stockStatus: "In Stock",
    stockQuantity: 145,
    rating: 4.7,
    reviewCount: 88,
    shortDescription: "High efficiency dry gas filter",
    longDescription: "Protects downstream equipment by removing dust, dirt, and pipe scale from natural gas lines.",
    specifications: {
      "Filtration": "5 microns",
      "Max Pressure": "16 bar",
      "Flow Capacity": "1000 Nm³/h",
      "Temperature Range": "-20°C to +80°C",
      "Material": "Aluminum body",
      "Element": "Pleated synthetic",
      "Connection": "DN50",
      "Options": "DP gauge port",
    },
    features: ["High dirt holding", "Low pressure drop", "Easy cartridge change", "O-ring sealed", "Compact", "Cost-effective"],
    applications: ["Meter protection", "Regulator protection", "Burner feeds"],
    imageId: images[21],
    galleryImages: [images[21], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-23",
    slug: "y-strainer-ys-200",
    name: "Y-Strainer YS-200",
    model: "YS-200",
    price: 180,
    category: "Filters & Strainers",
    stockStatus: "In Stock",
    stockQuantity: 200,
    rating: 4.5,
    reviewCount: 65,
    shortDescription: "Heavy duty cast iron Y-strainer",
    longDescription: "Simple, robust initial filtration to catch large debris in gas and liquid pipelines.",
    specifications: {
      "Mesh Size": "100 mesh (150 microns)",
      "Max Pressure": "40 bar",
      "Temperature Range": "-20°C to +150°C",
      "Material": "Cast Iron",
      "Screen": "Stainless Steel 304",
      "Connection": "Flanged DN100",
      "Blowdown": "Plugged port",
      "Certification": "PED",
    },
    features: ["Rugged design", "Cleanable screen", "Blowdown port", "Bi-directional", "Low cost", "Long lifespan"],
    applications: ["Pump protection", "Compressor inlets", "General pipeline"],
    imageId: images[22],
    galleryImages: [images[22], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-24",
    slug: "cartridge-filter-cf-50",
    name: "Cartridge Filter CF-50",
    model: "CF-50",
    price: 420,
    category: "Filters & Strainers",
    stockStatus: "In Stock",
    stockQuantity: 67,
    rating: 4.8,
    reviewCount: 43,
    shortDescription: "Coalescing filter for liquid removal",
    longDescription: "Advanced coalescing filter designed to remove aerosols, oil droplets, and fine particulates from gas streams.",
    specifications: {
      "Filtration": "0.3 microns",
      "Efficiency": "99.9%",
      "Max Pressure": "50 bar",
      "Temperature Range": "-10°C to +60°C",
      "Material": "Carbon Steel",
      "Element": "Micro-glass fiber",
      "Drain": "Auto/Manual dump",
      "Connection": "DN50",
    },
    features: ["Aerosol removal", "High efficiency", "Sight glass option", "Auto drain", "Heavy duty housing", "Differential gauge"],
    applications: ["Turbine protection", "Instrument air", "CNG stations"],
    imageId: images[23],
    galleryImages: [images[23], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-25",
    slug: "smart-logger-datalog-x",
    name: "Smart Logger DataLog-X",
    model: "DL-X",
    price: 850,
    category: "Gas Meters",
    stockStatus: "In Stock",
    stockQuantity: 40,
    rating: 4.7,
    reviewCount: 32,
    shortDescription: "Advanced telemetry and data logger",
    longDescription: "Universal data logger for gas meters, providing PTZ volume correction and 5G/LTE telemetry.",
    specifications: {
      "Inputs": "Pulse, NAMUR, 4-20mA",
      "Battery": "Lithium 5+ years",
      "Telemetry": "LTE-M, NB-IoT, 5G",
      "Display": "Backlit LCD",
      "Enclosure": "IP66 / NEMA 4X",
      "Correction": "PTZ, AGA8",
      "Memory": "10 million records",
      "Certification": "ATEX Zone 0",
    },
    features: ["Volume correction", "Multi-protocol", "Over the air updates", "Intrinsically safe", "Cloud sync", "Alarm notifications"],
    applications: ["Remote metering", "Network balancing", "Custody transfer"],
    imageId: images[24],
    galleryImages: [images[24], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-26",
    slug: "h2-analyzer-pro",
    name: "H2 Analyzer Pro",
    model: "H2A-PRO",
    price: 3200,
    category: "Hydrogen Systems",
    stockStatus: "In Stock",
    stockQuantity: 14,
    rating: 4.9,
    reviewCount: 18,
    shortDescription: "Real-time hydrogen blend analyzer",
    longDescription: "Fast response thermal conductivity analyzer for precise determination of H2 concentration in natural gas blends.",
    specifications: {
      "Range": "0-100% H2",
      "Accuracy": "±0.5% Full Scale",
      "Response Time": "T90 < 2 sec",
      "Operating Temp": "-20 to 55°C",
      "Output": "4-20mA, Modbus",
      "Power": "24 VDC",
      "Calibration": "Auto zero/span",
      "Certification": "ATEX Zone 1",
    },
    features: ["Drift-free", "No moving parts", "In-line probe", "Touch screen", "Low maintenance", "Plug and play"],
    applications: ["Blending skids", "Biogas injection", "Process control"],
    imageId: images[25],
    galleryImages: [images[25], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-27",
    slug: "pilot-filter-pf-10",
    name: "Pilot Filter PF-10",
    model: "PF-10",
    price: 150,
    category: "Filters & Strainers",
    stockStatus: "In Stock",
    stockQuantity: 120,
    rating: 4.6,
    reviewCount: 45,
    shortDescription: "High pressure pilot supply filter",
    longDescription: "Protects sensitive pilot regulators from fine particulate contamination in high pressure lines.",
    specifications: {
      "Filtration": "3 microns",
      "Max Pressure": "250 bar",
      "Flow Capacity": "100 Nm³/h",
      "Temperature Range": "-40°C to +80°C",
      "Material": "Stainless Steel",
      "Element": "Sintered metal",
      "Connection": "1/4\" NPT",
      "Certification": "NACE MR0175",
    },
    features: ["High pressure rated", "Stainless steel mesh", "Cleanable", "Compact size", "Easy mounting", "Corrosion resistant"],
    applications: ["Pilot supply", "Instrument gas", "Sampling systems"],
    imageId: images[26],
    galleryImages: [images[26], ...defaultGallery.slice(1)],
    downloads: [],
  },
  {
    id: "prod-28",
    slug: "emergency-shutdown-unit",
    name: "Emergency Shutdown Unit",
    model: "ESD-U",
    price: 3500,
    category: "Safety Valves",
    stockStatus: "In Stock",
    stockQuantity: 8,
    rating: 5.0,
    reviewCount: 14,
    shortDescription: "Remote emergency shutdown system",
    longDescription: "Complete unit for remote or local emergency shutdown of gas facilities. SIL3 certified reliability.",
    specifications: {
      "Actuation": "Pneumatic / Hydraulic",
      "Control": "Solenoid operated",
      "Response Time": "<2s",
      "Max Pressure": "100 bar",
      "Material": "Low temp Carbon Steel",
      "Certification": "SIL3, ATEX, IECEx",
    },
    features: ["Fail-safe", "Remote monitoring", "Manual override", "Fire proof option", "Explosion proof", "Diagnostic capability"],
    applications: ["Plant inlets", "Storage tanks", "Transmission hubs"],
    imageId: images[27],
    galleryImages: [images[27], ...defaultGallery.slice(1)],
    downloads: [],
  }
];
